use_frameworks!

target 'LYANRTracker_Example' do
  pod 'LYANRTracker', :path => '../'

  target 'LYANRTracker_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
